### PR TITLE
use env var sdx.env

### PR DESCRIPTION
**Pull request by dgunthor**

### CODE REVIEW

**Comment by iwootten** [comment]
What's this pull request for? The description is empty.

**Comment by dgunthor** [comment]
Makes the environment configurable for the ftp path location - preprod,
PROD, sit

**Comment by iwootten** [comment]
Ok, cool - probably need to ensure the title / descriptions of requests aren't commit descriptions or left empty, for the purposes of review.

**Comment by dgunthor** [comment]
this can be deleted shortly - DO NOT MERGE!

**Pull request merged**
